version: '3'

services:
    app-server:
        build:
            context: .
        container_name: risqc-server
        volumes:
            - ./:/home/app
        ports:
            - "4004:4004"
    db:
        image: mysql
        restart: always
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: risqc
        command: mysqld --init-file="/tmp/database/init.sql"
        volumes:
         - ./data:/var/lib/mysql
         - ./db_init:/tmp/database
volumes:
  data:
  db_init: